### ISSUE TITLE
Love the new features. 😄 but I've found 2 bugs

### ISSUE THREAD

**Issue by omariparris** [mlfarrell/VertoJS-VertoStudio3D#2]
The first one I'm not sure if its actually a bug or I'm doing something wrong but the weight painting doesn't work. https://user-images.githubusercontent.com/68160962/222308416-024c89e6-1341-497c-87bb-c42a5caaedf6.MOV

Second one is that whenever you delete a joint in edit mode the app crashes.

Will keep testing extensively

**Comment by omariparris** [comment]
AH About the first one, The weight painting only works in Perspective mode

**Comment by mlfarrell** [comment]
This repo is strictly for the JS/scripting scripts. Not intended for verto 3D editor itself.  

Please use the Discord for general support for the app  

having said that, I will take a look at both of these, and thank you for reporting it

I likely will close this issue on here in a few days

**Comment by omariparris** [comment]
> 

Ah okay, could you share a link to the discord?

**Comment by mlfarrell** [comment]
I remember, testing deleting skeleton joints, quite extensively, even after they are bound. But you might’ve found some issue related editing skeletons that are bound.  I’d like a video of that so I can see what happened (again to the discord, not here)

Discord is available from multiple places in the app, either the tiny “I” button, or on the top bar of the library screen icon with the multiple heads

**Comment by omariparris** [comment]
> I remember, testing deleting skeleton joints, quite extensively, even after they are bound. But you might’ve found some issue related editing skeletons that are bound. I’d like a video of that so I can see what happened (again to the discord, not here)
> 
> Discord is available from multiple places in the app, either the tiny “I” button, or on the top bar of the library screen icon with the multiple heads

Okay great I'll head over there now. Will send the crash video also
